<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="a5cd1dd3-4167-410f-8fa5-f0bffeb44dfa" name="305024278@305024278-PC 2012-01-20 17:38:18" runUser="305024278-PC\305024278" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="f71d3d1c-fcb9-4cb8-bd16-ef1b721fb9d0">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="305024278_305024278-PC 2012-01-20 17_38_18">
      <DeploymentItem filename="D:\GitRepositories\MyStory\packages\WebActivator.1.0.0.0\lib\WebActivator.dll" />
      <DeploymentItem filename="D:\GitRepositories\MyStory\packages\elmah.corelibrary.1.2\lib\Elmah.dll" />
      <DeploymentItem filename="D:\GitRepositories\MyStory\packages\EntityFramework.SqlServerCompact.4.1.8482.2\lib\System.Data.SqlServerCe.Entity.dll" />
      <DeploymentItem filename="D:\GitRepositories\MyStory\packages\EntityFramework.4.2.0.0\lib\net40\EntityFramework.dll" />
      <DeploymentItem filename="D:\GitRepositories\MyStory\packages\AutoMapper.1.1.0.118\lib\AutoMapper.dll" />
      <DeploymentItem filename="D:\GitRepositories\MyStory\MyStory\bin\MyStory.dll" />
      <DeploymentItem filename="D:\GitRepositories\MyStory\packages\SqlServerCompact.4.0.8482.1\lib\System.Data.SqlServerCe.dll" />
      <DeploymentItem filename="D:\GitRepositories\MyStory\packages\Moq.4.0.10827\lib\NET40\Moq.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2012-01-20T17:38:18.3619155+09:00" queuing="2012-01-20T17:38:18.5589267+09:00" start="2012-01-20T17:38:18.5889284+09:00" finish="2012-01-20T17:38:20.1730190+09:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="edit_should_return_postmodel" storage="d:\gitrepositories\mystory\mystory.tests\bin\debug\mystory.tests.dll" id="f3f6c189-c024-def3-868c-96d0a78f5400">
      <Execution id="fa4b5065-9b63-44d5-b574-6c5035af7159" />
      <TestMethod codeBase="D:/GitRepositories/MyStory/MyStory.Tests/bin/Debug/MyStory.Tests.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="MyStory.Tests.IntegrationTests.Controllers.PostControllerTest, MyStory.Tests, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="edit_should_return_postmodel" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="f3f6c189-c024-def3-868c-96d0a78f5400" executionId="fa4b5065-9b63-44d5-b574-6c5035af7159" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="fa4b5065-9b63-44d5-b574-6c5035af7159" testId="f3f6c189-c024-def3-868c-96d0a78f5400" testName="edit_should_return_postmodel" computerName="305024278-PC" duration="00:00:01.3214550" startTime="2012-01-20T17:38:18.5979290+09:00" endTime="2012-01-20T17:38:20.1460175+09:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="fa4b5065-9b63-44d5-b574-6c5035af7159">
      <Output>
        <ErrorInfo>
          <Message>Test method MyStory.Tests.IntegrationTests.Controllers.PostControllerTest.edit_should_return_postmodel threw exception: 
System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---&gt; System.Data.UpdateException: An error occurred while updating the entries. See the inner exception for details. ---&gt; System.Data.SqlServerCe.SqlCeException: datetime으로 변환하는 동안 오버플로가 발생했습니다.</Message>
          <StackTrace>    at System.Data.SqlServerCe.SqlCeCommand.ProcessResults(Int32 hr)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommandText(IntPtr&amp; pCursor, Boolean&amp; isBaseTableCursor)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteCommand(CommandBehavior behavior, String method, ResultSetOptions options)
   at System.Data.SqlServerCe.SqlCeCommand.ExecuteNonQuery()
   at System.Data.SqlServerCe.SqlCeMultiCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlServerCe.SqlCeMultiCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Mapping.Update.Internal.DynamicUpdateCommand.Execute(UpdateTranslator translator, EntityConnection connection, Dictionary`2 identifierValues, List`1 generatedValues)
   at System.Data.Mapping.Update.Internal.UpdateTranslator.Update(IEntityStateManager stateManager, IEntityAdapter adapter)
 --- End of inner exception stack trace ---
    at System.Data.Mapping.Update.Internal.UpdateTranslator.Update(IEntityStateManager stateManager, IEntityAdapter adapter)
   at System.Data.EntityClient.EntityAdapter.Update(IEntityStateManager entityCache)
   at System.Data.Objects.ObjectContext.SaveChanges(SaveOptions options)
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
 --- End of inner exception stack trace ---
    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at System.Data.Entity.DbContext.SaveChanges()
   at MyStory.Tests.IntegrationTests.Controllers.PostControllerTest.edit_should_return_postmodel() in D:\GitRepositories\MyStory\MyStory.Tests\IntegrationTests\Controllers\PostControllerTest.cs:line 79
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>